# Generated by Django 4.1 on 2022-08-10 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_films', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstats',
            options={'ordering': ['-value'], 'verbose_name': 'Звезда рейтинга', 'verbose_name_plural': 'Звезды рейтинга'},
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='stat',
            new_name='star',
        ),
    ]
